/* tslint:disable */
/* eslint-disable */
/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ResendTokenRequest } from '../models';
/**
 * ConfirmationTokenControllerApi - axios parameter creator
 */
export const ConfirmationTokenControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ResendTokenRequest} resendTokenRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resendToken: async (resendTokenRequest: ResendTokenRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'resendTokenRequest' is not null or undefined
            assertParamExists('resendToken', 'resendTokenRequest', resendTokenRequest)
            const localVarPath = `/api/v1/token/resend`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(resendTokenRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyChangeEmail: async (token: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('verifyChangeEmail', 'token', token)
            const localVarPath = `/api/v1/token/verify-change`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (token !== undefined) {
                localVarQueryParameter['token'] = token;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyToken: async (token: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('verifyToken', 'token', token)
            const localVarPath = `/api/v1/token/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (token !== undefined) {
                localVarQueryParameter['token'] = token;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ConfirmationTokenControllerApi - functional programming interface
 */
export const ConfirmationTokenControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ConfirmationTokenControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {ResendTokenRequest} resendTokenRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resendToken(resendTokenRequest: ResendTokenRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resendToken(resendTokenRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConfirmationTokenControllerApi.resendToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verifyChangeEmail(token: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.verifyChangeEmail(token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConfirmationTokenControllerApi.verifyChangeEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verifyToken(token: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.verifyToken(token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConfirmationTokenControllerApi.verifyToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ConfirmationTokenControllerApi - factory interface
 */
export const ConfirmationTokenControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ConfirmationTokenControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {ConfirmationTokenControllerApiResendTokenRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resendToken(requestParameters: ConfirmationTokenControllerApiResendTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.resendToken(requestParameters.resendTokenRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ConfirmationTokenControllerApiVerifyChangeEmailRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyChangeEmail(requestParameters: ConfirmationTokenControllerApiVerifyChangeEmailRequest, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.verifyChangeEmail(requestParameters.token, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ConfirmationTokenControllerApiVerifyTokenRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyToken(requestParameters: ConfirmationTokenControllerApiVerifyTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.verifyToken(requestParameters.token, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for resendToken operation in ConfirmationTokenControllerApi.
 */
export interface ConfirmationTokenControllerApiResendTokenRequest {
    readonly resendTokenRequest: ResendTokenRequest
}

/**
 * Request parameters for verifyChangeEmail operation in ConfirmationTokenControllerApi.
 */
export interface ConfirmationTokenControllerApiVerifyChangeEmailRequest {
    readonly token: string
}

/**
 * Request parameters for verifyToken operation in ConfirmationTokenControllerApi.
 */
export interface ConfirmationTokenControllerApiVerifyTokenRequest {
    readonly token: string
}

/**
 * ConfirmationTokenControllerApi - object-oriented interface
 */
export class ConfirmationTokenControllerApi extends BaseAPI {
    /**
     * 
     * @param {ConfirmationTokenControllerApiResendTokenRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public resendToken(requestParameters: ConfirmationTokenControllerApiResendTokenRequest, options?: RawAxiosRequestConfig) {
        return ConfirmationTokenControllerApiFp(this.configuration).resendToken(requestParameters.resendTokenRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ConfirmationTokenControllerApiVerifyChangeEmailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public verifyChangeEmail(requestParameters: ConfirmationTokenControllerApiVerifyChangeEmailRequest, options?: RawAxiosRequestConfig) {
        return ConfirmationTokenControllerApiFp(this.configuration).verifyChangeEmail(requestParameters.token, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ConfirmationTokenControllerApiVerifyTokenRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public verifyToken(requestParameters: ConfirmationTokenControllerApiVerifyTokenRequest, options?: RawAxiosRequestConfig) {
        return ConfirmationTokenControllerApiFp(this.configuration).verifyToken(requestParameters.token, options).then((request) => request(this.axios, this.basePath));
    }
}

