/* tslint:disable */
/* eslint-disable */
/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FinancialData } from './financial-data';
// May contain unused imports in some cases
// @ts-ignore
import type { PropertyData } from './property-data';
// May contain unused imports in some cases
// @ts-ignore
import type { UserData } from './user-data';

export interface InitialContractResponse {
    'id'?: number;
    'created_at'?: string;
    'expire_at'?: string;
    'owner_data'?: UserData;
    'seeker_data'?: UserData;
    'property_data'?: PropertyData;
    'financial_data'?: FinancialData;
    'status'?: InitialContractResponseStatusEnum;
}

export const InitialContractResponseStatusEnum = {
    PendingApproval: 'PENDING_APPROVAL',
    PendingProcessing: 'PENDING_PROCESSING',
    UnderProcess: 'UNDER_PROCESS',
    Completed: 'COMPLETED',
    Reject: 'REJECT',
    Expired: 'EXPIRED',
    Banned: 'BANNED',
} as const;

export type InitialContractResponseStatusEnum = typeof InitialContractResponseStatusEnum[keyof typeof InitialContractResponseStatusEnum];


