/* tslint:disable */
/* eslint-disable */
/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BlogAdminsResponse } from './blog-admins-response';

export interface PageResponseBlogAdminsResponse {
    'content'?: Array<BlogAdminsResponse>;
    'totalPages'?: number;
    'totalElements'?: number;
    'page'?: number;
    'size'?: number;
    'last'?: boolean;
}

