/* tslint:disable */
/* eslint-disable */
/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Features } from './features';
// May contain unused imports in some cases
// @ts-ignore
import type { GeoJsonPoint } from './geo-json-point';
// May contain unused imports in some cases
// @ts-ignore
import type { Image } from './image';
// May contain unused imports in some cases
// @ts-ignore
import type { Location } from './location';
// May contain unused imports in some cases
// @ts-ignore
import type { Review } from './review';

export interface Property {
    'id'?: string;
    'title'?: string;
    'price'?: number;
    'type'?: PropertyTypeEnum;
    'ownerId'?: number;
    'status'?: PropertyStatusEnum;
    'features'?: Features;
    'mapsLocation'?: GeoJsonPoint;
    'location'?: Location;
    'images'?: Array<Image>;
    'description'?: string;
    'review'?: Review;
    'createdAt'?: string;
    'deletedAt'?: string;
}

export const PropertyTypeEnum = {
    Rent: 'RENT',
    Purchase: 'PURCHASE',
    CommercialRent: 'COMMERCIAL_RENT',
    CommercialPurchase: 'COMMERCIAL_PURCHASE',
    Student: 'STUDENT',
} as const;

export type PropertyTypeEnum = typeof PropertyTypeEnum[keyof typeof PropertyTypeEnum];
export const PropertyStatusEnum = {
    Available: 'AVAILABLE',
    PendingProcessing: 'PENDING_PROCESSING',
    Completed: 'COMPLETED',
    Banned: 'BANNED',
} as const;

export type PropertyStatusEnum = typeof PropertyStatusEnum[keyof typeof PropertyStatusEnum];


