/* tslint:disable */
/* eslint-disable */
/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PropertyAdPostRequest {
    'title': string;
    'price': number;
    'type': PropertyAdPostRequestTypeEnum;
    'lng': number;
    'lat': number;
    'description'?: string;
    'rooms'?: number;
    'baths'?: number;
    'images'?: Array<File>;
    'city': string;
    'area': string;
    'size': number;
}

export const PropertyAdPostRequestTypeEnum = {
    Rent: 'RENT',
    Purchase: 'PURCHASE',
    CommercialRent: 'COMMERCIAL_RENT',
    CommercialPurchase: 'COMMERCIAL_PURCHASE',
    Student: 'STUDENT',
} as const;

export type PropertyAdPostRequestTypeEnum = typeof PropertyAdPostRequestTypeEnum[keyof typeof PropertyAdPostRequestTypeEnum];


