/* tslint:disable */
/* eslint-disable */
/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Features } from './features';
// May contain unused imports in some cases
// @ts-ignore
import type { Review } from './review';

export interface PropertyAdminResponse {
    'id'?: string;
    'title'?: string;
    'owner'?: string;
    'decription'?: string;
    'price'?: number;
    'type'?: PropertyAdminResponseTypeEnum;
    'status'?: PropertyAdminResponseStatusEnum;
    'features'?: Features;
    'coordinates'?: Array<number>;
    'city'?: string;
    'area'?: string;
    'review'?: Review;
}

export const PropertyAdminResponseTypeEnum = {
    Rent: 'RENT',
    Purchase: 'PURCHASE',
    CommercialRent: 'COMMERCIAL_RENT',
    CommercialPurchase: 'COMMERCIAL_PURCHASE',
    Student: 'STUDENT',
} as const;

export type PropertyAdminResponseTypeEnum = typeof PropertyAdminResponseTypeEnum[keyof typeof PropertyAdminResponseTypeEnum];
export const PropertyAdminResponseStatusEnum = {
    Available: 'AVAILABLE',
    PendingProcessing: 'PENDING_PROCESSING',
    Completed: 'COMPLETED',
    Banned: 'BANNED',
} as const;

export type PropertyAdminResponseStatusEnum = typeof PropertyAdminResponseStatusEnum[keyof typeof PropertyAdminResponseStatusEnum];


