/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiClient);
  }
}(this, function(expect, ApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiClient.AdminControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AdminControllerApi', function() {
    describe('addBlog', function() {
      it('should call addBlog successfully', function(done) {
        //uncomment below and update the code to test addBlog
        //instance.addBlog(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('callDelete', function() {
      it('should call callDelete successfully', function(done) {
        //uncomment below and update the code to test callDelete
        //instance.callDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteBlog', function() {
      it('should call deleteBlog successfully', function(done) {
        //uncomment below and update the code to test deleteBlog
        //instance.deleteBlog(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteProperty', function() {
      it('should call deleteProperty successfully', function(done) {
        //uncomment below and update the code to test deleteProperty
        //instance.deleteProperty(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAdmins', function() {
      it('should call getAdmins successfully', function(done) {
        //uncomment below and update the code to test getAdmins
        //instance.getAdmins(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBlogs', function() {
      it('should call getBlogs successfully', function(done) {
        //uncomment below and update the code to test getBlogs
        //instance.getBlogs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLawyers', function() {
      it('should call getLawyers successfully', function(done) {
        //uncomment below and update the code to test getLawyers
        //instance.getLawyers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProperties1', function() {
      it('should call getProperties1 successfully', function(done) {
        //uncomment below and update the code to test getProperties1
        //instance.getProperties1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUsers', function() {
      it('should call getUsers successfully', function(done) {
        //uncomment below and update the code to test getUsers
        //instance.getUsers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registerAdmin', function() {
      it('should call registerAdmin successfully', function(done) {
        //uncomment below and update the code to test registerAdmin
        //instance.registerAdmin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registerLawyer', function() {
      it('should call registerLawyer successfully', function(done) {
        //uncomment below and update the code to test registerLawyer
        //instance.registerLawyer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registerUser', function() {
      it('should call registerUser successfully', function(done) {
        //uncomment below and update the code to test registerUser
        //instance.registerUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchAdmin', function() {
      it('should call searchAdmin successfully', function(done) {
        //uncomment below and update the code to test searchAdmin
        //instance.searchAdmin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchBlog', function() {
      it('should call searchBlog successfully', function(done) {
        //uncomment below and update the code to test searchBlog
        //instance.searchBlog(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchLawyer', function() {
      it('should call searchLawyer successfully', function(done) {
        //uncomment below and update the code to test searchLawyer
        //instance.searchLawyer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchProperty', function() {
      it('should call searchProperty successfully', function(done) {
        //uncomment below and update the code to test searchProperty
        //instance.searchProperty(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchUser', function() {
      it('should call searchUser successfully', function(done) {
        //uncomment below and update the code to test searchUser
        //instance.searchUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateBlog', function() {
      it('should call updateBlog successfully', function(done) {
        //uncomment below and update the code to test updateBlog
        //instance.updateBlog(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
