/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiClient);
  }
}(this, function(expect, ApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiClient.LawyerControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LawyerControllerApi', function() {
    describe('banContract', function() {
      it('should call banContract successfully', function(done) {
        //uncomment below and update the code to test banContract
        //instance.banContract(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cancelContract', function() {
      it('should call cancelContract successfully', function(done) {
        //uncomment below and update the code to test cancelContract
        //instance.cancelContract(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('completeContract', function() {
      it('should call completeContract successfully', function(done) {
        //uncomment below and update the code to test completeContract
        //instance.completeContract(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getContract', function() {
      it('should call getContract successfully', function(done) {
        //uncomment below and update the code to test getContract
        //instance.getContract(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMyContracts', function() {
      it('should call getMyContracts successfully', function(done) {
        //uncomment below and update the code to test getMyContracts
        //instance.getMyContracts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPendingContracts', function() {
      it('should call getPendingContracts successfully', function(done) {
        //uncomment below and update the code to test getPendingContracts
        //instance.getPendingContracts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('workingOnContract', function() {
      it('should call workingOnContract successfully', function(done) {
        //uncomment below and update the code to test workingOnContract
        //instance.workingOnContract(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
