/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiClient);
  }
}(this, function(expect, ApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiClient.InitialContractCreationRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InitialContractCreationRequest', function() {
    it('should create an instance of InitialContractCreationRequest', function() {
      // uncomment below and update the code to test InitialContractCreationRequest
      //var instance = new ApiClient.InitialContractCreationRequest();
      //expect(instance).to.be.a(ApiClient.InitialContractCreationRequest);
    });

    it('should have the property propertyId (base name: "property_id")', function() {
      // uncomment below and update the code to test the property propertyId
      //var instance = new ApiClient.InitialContractCreationRequest();
      //expect(instance).to.be();
    });

    it('should have the property rentDuration (base name: "rentDuration")', function() {
      // uncomment below and update the code to test the property rentDuration
      //var instance = new ApiClient.InitialContractCreationRequest();
      //expect(instance).to.be();
    });

  });

}));
