/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiClient);
  }
}(this, function(expect, ApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiClient.InitialContractResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InitialContractResponse', function() {
    it('should create an instance of InitialContractResponse', function() {
      // uncomment below and update the code to test InitialContractResponse
      //var instance = new ApiClient.InitialContractResponse();
      //expect(instance).to.be.a(ApiClient.InitialContractResponse);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ApiClient.InitialContractResponse();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new ApiClient.InitialContractResponse();
      //expect(instance).to.be();
    });

    it('should have the property expireAt (base name: "expire_at")', function() {
      // uncomment below and update the code to test the property expireAt
      //var instance = new ApiClient.InitialContractResponse();
      //expect(instance).to.be();
    });

    it('should have the property ownerData (base name: "owner_data")', function() {
      // uncomment below and update the code to test the property ownerData
      //var instance = new ApiClient.InitialContractResponse();
      //expect(instance).to.be();
    });

    it('should have the property seekerData (base name: "seeker_data")', function() {
      // uncomment below and update the code to test the property seekerData
      //var instance = new ApiClient.InitialContractResponse();
      //expect(instance).to.be();
    });

    it('should have the property propertyData (base name: "property_data")', function() {
      // uncomment below and update the code to test the property propertyData
      //var instance = new ApiClient.InitialContractResponse();
      //expect(instance).to.be();
    });

    it('should have the property financialData (base name: "financial_data")', function() {
      // uncomment below and update the code to test the property financialData
      //var instance = new ApiClient.InitialContractResponse();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new ApiClient.InitialContractResponse();
      //expect(instance).to.be();
    });

  });

}));
