/* tslint:disable */
/* eslint-disable */
/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './apis/admin-controller-api';
export * from './apis/app-user-controller-api';
export * from './apis/blog-controller-api';
export * from './apis/change-info-controller-api';
export * from './apis/confirmation-token-controller-api';
export * from './apis/forgot-password-controller-api';
export * from './apis/initial-contract-controller-api';
export * from './apis/keep-alive-api';
export * from './apis/lawyer-controller-api';
export * from './apis/login-controller-api';
export * from './apis/notification-controller-api';
export * from './apis/property-controller-api';
export * from './apis/recommendation-controller-api';
export * from './apis/registration-controller-api';
export * from './apis/reset-password-controller-api';
export * from './apis/seved-property-controller-api';

