/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DisableRequest from '../model/DisableRequest';

/**
* AppUserController service.
* @module api/AppUserControllerApi
* @version V1.0
*/
export default class AppUserControllerApi {

    /**
    * Constructs a new AppUserControllerApi. 
    * @alias module:api/AppUserControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {module:model/DisableRequest} disableRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    disableAccountWithHttpInfo(disableRequest) {
      let postBody = disableRequest;
      // verify the required parameter 'disableRequest' is set
      if (disableRequest === undefined || disableRequest === null) {
        throw new Error("Missing the required parameter 'disableRequest' when calling disableAccount");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/users', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {module:model/DisableRequest} disableRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    disableAccount(disableRequest) {
      return this.disableAccountWithHttpInfo(disableRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
