/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ChangeEmailRequest from '../model/ChangeEmailRequest';
import ChangePasswordRequest from '../model/ChangePasswordRequest';
import ChangePhoneRequest from '../model/ChangePhoneRequest';

/**
* ChangeInfoController service.
* @module api/ChangeInfoControllerApi
* @version V1.0
*/
export default class ChangeInfoControllerApi {

    /**
    * Constructs a new ChangeInfoControllerApi. 
    * @alias module:api/ChangeInfoControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {module:model/ChangeEmailRequest} changeEmailRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    changeEmailWithHttpInfo(changeEmailRequest) {
      let postBody = changeEmailRequest;
      // verify the required parameter 'changeEmailRequest' is set
      if (changeEmailRequest === undefined || changeEmailRequest === null) {
        throw new Error("Missing the required parameter 'changeEmailRequest' when calling changeEmail");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/change/email', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {module:model/ChangeEmailRequest} changeEmailRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    changeEmail(changeEmailRequest) {
      return this.changeEmailWithHttpInfo(changeEmailRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {module:model/ChangePasswordRequest} changePasswordRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    changePasswordWithHttpInfo(changePasswordRequest) {
      let postBody = changePasswordRequest;
      // verify the required parameter 'changePasswordRequest' is set
      if (changePasswordRequest === undefined || changePasswordRequest === null) {
        throw new Error("Missing the required parameter 'changePasswordRequest' when calling changePassword");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/change/password', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {module:model/ChangePasswordRequest} changePasswordRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    changePassword(changePasswordRequest) {
      return this.changePasswordWithHttpInfo(changePasswordRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {module:model/ChangePhoneRequest} changePhoneRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    changePhoneWithHttpInfo(changePhoneRequest) {
      let postBody = changePhoneRequest;
      // verify the required parameter 'changePhoneRequest' is set
      if (changePhoneRequest === undefined || changePhoneRequest === null) {
        throw new Error("Missing the required parameter 'changePhoneRequest' when calling changePhone");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/change/phone', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {module:model/ChangePhoneRequest} changePhoneRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    changePhone(changePhoneRequest) {
      return this.changePhoneWithHttpInfo(changePhoneRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
