/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ForgotPasswordRequest from '../model/ForgotPasswordRequest';

/**
* ForgotPasswordController service.
* @module api/ForgotPasswordControllerApi
* @version V1.0
*/
export default class ForgotPasswordControllerApi {

    /**
    * Constructs a new ForgotPasswordControllerApi. 
    * @alias module:api/ForgotPasswordControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {module:model/ForgotPasswordRequest} forgotPasswordRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object.<String, {String: String}>} and HTTP response
     */
    forgotPasswordWithHttpInfo(forgotPasswordRequest) {
      let postBody = forgotPasswordRequest;
      // verify the required parameter 'forgotPasswordRequest' is set
      if (forgotPasswordRequest === undefined || forgotPasswordRequest === null) {
        throw new Error("Missing the required parameter 'forgotPasswordRequest' when calling forgotPassword");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = {'String': 'String'};
      return this.apiClient.callApi(
        '/api/v1/forgot-password', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {module:model/ForgotPasswordRequest} forgotPasswordRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object.<String, {String: String}>}
     */
    forgotPassword(forgotPasswordRequest) {
      return this.forgotPasswordWithHttpInfo(forgotPasswordRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
