/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PageResponsePropertyBriefResponse from '../model/PageResponsePropertyBriefResponse';
import Property from '../model/Property';
import PropertyAdCreationResponse from '../model/PropertyAdCreationResponse';
import PropertyAdPostRequest from '../model/PropertyAdPostRequest';
import PropertyBriefResponse from '../model/PropertyBriefResponse';
import PropertyDetailedResponse from '../model/PropertyDetailedResponse';
import PropertyPatchRequest from '../model/PropertyPatchRequest';
import ReviewRequest from '../model/ReviewRequest';

/**
* PropertyController service.
* @module api/PropertyControllerApi
* @version V1.0
*/
export default class PropertyControllerApi {

    /**
    * Constructs a new PropertyControllerApi. 
    * @alias module:api/PropertyControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {module:model/PropertyAdPostRequest} propertyAdPostRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PropertyAdCreationResponse} and HTTP response
     */
    addPropertyAdWithHttpInfo(propertyAdPostRequest) {
      let postBody = propertyAdPostRequest;
      // verify the required parameter 'propertyAdPostRequest' is set
      if (propertyAdPostRequest === undefined || propertyAdPostRequest === null) {
        throw new Error("Missing the required parameter 'propertyAdPostRequest' when calling addPropertyAd");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = PropertyAdCreationResponse;
      return this.apiClient.callApi(
        '/api/v1/properties', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {module:model/PropertyAdPostRequest} propertyAdPostRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PropertyAdCreationResponse}
     */
    addPropertyAd(propertyAdPostRequest) {
      return this.addPropertyAdWithHttpInfo(propertyAdPostRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {String} id 
     * @param {module:model/PropertyPatchRequest} propertyPatchRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    changePropertyAdWithHttpInfo(id, propertyPatchRequest) {
      let postBody = propertyPatchRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling changePropertyAd");
      }
      // verify the required parameter 'propertyPatchRequest' is set
      if (propertyPatchRequest === undefined || propertyPatchRequest === null) {
        throw new Error("Missing the required parameter 'propertyPatchRequest' when calling changePropertyAd");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/properties/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {String} id 
     * @param {module:model/PropertyPatchRequest} propertyPatchRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    changePropertyAd(id, propertyPatchRequest) {
      return this.changePropertyAdWithHttpInfo(id, propertyPatchRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    deletePropertyAdWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deletePropertyAd");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/properties/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    deletePropertyAd(id) {
      return this.deletePropertyAdWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Property>} and HTTP response
     */
    getMyPropertiesWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [Property];
      return this.apiClient.callApi(
        '/api/v1/properties/my-properties', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Property>}
     */
    getMyProperties() {
      return this.getMyPropertiesWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PropertyDetailedResponse} and HTTP response
     */
    getMyPropertyWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getMyProperty");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = PropertyDetailedResponse;
      return this.apiClient.callApi(
        '/api/v1/properties/my-property/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PropertyDetailedResponse}
     */
    getMyProperty(id) {
      return this.getMyPropertyWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 0)] 
     * @param {Number} [size = 20)] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PageResponsePropertyBriefResponse} and HTTP response
     */
    getPropertiesWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = PageResponsePropertyBriefResponse;
      return this.apiClient.callApi(
        '/api/v1/properties', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page  (default to 0)
     * @param {Number} opts.size  (default to 20)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PageResponsePropertyBriefResponse}
     */
    getProperties(opts) {
      return this.getPropertiesWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PropertyDetailedResponse} and HTTP response
     */
    getPropertyWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getProperty");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = PropertyDetailedResponse;
      return this.apiClient.callApi(
        '/api/v1/properties/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PropertyDetailedResponse}
     */
    getProperty(id) {
      return this.getPropertyWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {String} id 
     * @param {module:model/ReviewRequest} reviewRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    ratePropertyAdWithHttpInfo(id, reviewRequest) {
      let postBody = reviewRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling ratePropertyAd");
      }
      // verify the required parameter 'reviewRequest' is set
      if (reviewRequest === undefined || reviewRequest === null) {
        throw new Error("Missing the required parameter 'reviewRequest' when calling ratePropertyAd");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/properties/rating/{id}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {String} id 
     * @param {module:model/ReviewRequest} reviewRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    ratePropertyAd(id, reviewRequest) {
      return this.ratePropertyAdWithHttpInfo(id, reviewRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {Number} lng 
     * @param {Number} lat 
     * @param {Object} opts Optional parameters
     * @param {Number} [maxDistance] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/PropertyBriefResponse>} and HTTP response
     */
    searchByCoordinatesWithHttpInfo(lng, lat, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'lng' is set
      if (lng === undefined || lng === null) {
        throw new Error("Missing the required parameter 'lng' when calling searchByCoordinates");
      }
      // verify the required parameter 'lat' is set
      if (lat === undefined || lat === null) {
        throw new Error("Missing the required parameter 'lat' when calling searchByCoordinates");
      }

      let pathParams = {
      };
      let queryParams = {
        'lng': lng,
        'lat': lat,
        'maxDistance': opts['maxDistance']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [PropertyBriefResponse];
      return this.apiClient.callApi(
        '/api/v1/properties/search/coord', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {Number} lng 
     * @param {Number} lat 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.maxDistance 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/PropertyBriefResponse>}
     */
    searchByCoordinates(lng, lat, opts) {
      return this.searchByCoordinatesWithHttpInfo(lng, lat, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {Object} opts Optional parameters
     * @param {module:model/String} [type] 
     * @param {String} [city] 
     * @param {String} [area] 
     * @param {Number} [minRooms] 
     * @param {Number} [maxRooms] 
     * @param {Number} [minBaths] 
     * @param {Number} [maxBaths] 
     * @param {Number} [minPrice] 
     * @param {Number} [maxPrice] 
     * @param {Number} [minSize] 
     * @param {Number} [maxSize] 
     * @param {Number} [page = 0)] 
     * @param {Number} [size = 20)] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PageResponsePropertyBriefResponse} and HTTP response
     */
    searchByFiltersWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'type': opts['type'],
        'city': opts['city'],
        'area': opts['area'],
        'minRooms': opts['minRooms'],
        'maxRooms': opts['maxRooms'],
        'minBaths': opts['minBaths'],
        'maxBaths': opts['maxBaths'],
        'minPrice': opts['minPrice'],
        'maxPrice': opts['maxPrice'],
        'minSize': opts['minSize'],
        'maxSize': opts['maxSize'],
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = PageResponsePropertyBriefResponse;
      return this.apiClient.callApi(
        '/api/v1/properties/search/filter', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.type 
     * @param {String} opts.city 
     * @param {String} opts.area 
     * @param {Number} opts.minRooms 
     * @param {Number} opts.maxRooms 
     * @param {Number} opts.minBaths 
     * @param {Number} opts.maxBaths 
     * @param {Number} opts.minPrice 
     * @param {Number} opts.maxPrice 
     * @param {Number} opts.minSize 
     * @param {Number} opts.maxSize 
     * @param {Number} opts.page  (default to 0)
     * @param {Number} opts.size  (default to 20)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PageResponsePropertyBriefResponse}
     */
    searchByFilters(opts) {
      return this.searchByFiltersWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {String} text 
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 0)] 
     * @param {Number} [size = 20)] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PageResponsePropertyBriefResponse} and HTTP response
     */
    searchByTextWithHttpInfo(text, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'text' is set
      if (text === undefined || text === null) {
        throw new Error("Missing the required parameter 'text' when calling searchByText");
      }

      let pathParams = {
      };
      let queryParams = {
        'text': text,
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = PageResponsePropertyBriefResponse;
      return this.apiClient.callApi(
        '/api/v1/properties/search', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {String} text 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page  (default to 0)
     * @param {Number} opts.size  (default to 20)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PageResponsePropertyBriefResponse}
     */
    searchByText(text, opts) {
      return this.searchByTextWithHttpInfo(text, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
