/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PropertyDetailedResponse from '../model/PropertyDetailedResponse';

/**
* RecommendationController service.
* @module api/RecommendationControllerApi
* @version V1.0
*/
export default class RecommendationControllerApi {

    /**
    * Constructs a new RecommendationControllerApi. 
    * @alias module:api/RecommendationControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/PropertyDetailedResponse>} and HTTP response
     */
    getRecommendationsWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [PropertyDetailedResponse];
      return this.apiClient.callApi(
        '/api/v1/recommendation', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/PropertyDetailedResponse>}
     */
    getRecommendations() {
      return this.getRecommendationsWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
