/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import RegistrationRequest from '../model/RegistrationRequest';
import RegistrationResponse from '../model/RegistrationResponse';

/**
* RegistrationController service.
* @module api/RegistrationControllerApi
* @version V1.0
*/
export default class RegistrationControllerApi {

    /**
    * Constructs a new RegistrationControllerApi. 
    * @alias module:api/RegistrationControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {module:model/RegistrationRequest} registrationRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RegistrationResponse} and HTTP response
     */
    registerWithHttpInfo(registrationRequest) {
      let postBody = registrationRequest;
      // verify the required parameter 'registrationRequest' is set
      if (registrationRequest === undefined || registrationRequest === null) {
        throw new Error("Missing the required parameter 'registrationRequest' when calling register");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = RegistrationResponse;
      return this.apiClient.callApi(
        '/api/v1/registration', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {module:model/RegistrationRequest} registrationRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RegistrationResponse}
     */
    register(registrationRequest) {
      return this.registerWithHttpInfo(registrationRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
