/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PropertyDetailedResponse from '../model/PropertyDetailedResponse';
import SavePropertyRequest from '../model/SavePropertyRequest';

/**
* SevedPropertyController service.
* @module api/SevedPropertyControllerApi
* @version V1.0
*/
export default class SevedPropertyControllerApi {

    /**
    * Constructs a new SevedPropertyControllerApi. 
    * @alias module:api/SevedPropertyControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/PropertyDetailedResponse>} and HTTP response
     */
    getMySavedPropertiesWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [PropertyDetailedResponse];
      return this.apiClient.callApi(
        '/api/v1/saved-properties', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/PropertyDetailedResponse>}
     */
    getMySavedProperties() {
      return this.getMySavedPropertiesWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    removeFromSavedWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling removeFromSaved");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/saved-properties/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    removeFromSaved(id) {
      return this.removeFromSavedWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {module:model/SavePropertyRequest} savePropertyRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    savePropertyWithHttpInfo(savePropertyRequest) {
      let postBody = savePropertyRequest;
      // verify the required parameter 'savePropertyRequest' is set
      if (savePropertyRequest === undefined || savePropertyRequest === null) {
        throw new Error("Missing the required parameter 'savePropertyRequest' when calling saveProperty");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1/saved-properties', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {module:model/SavePropertyRequest} savePropertyRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    saveProperty(savePropertyRequest) {
      return this.savePropertyWithHttpInfo(savePropertyRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
