/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BlogAdminsResponse model module.
 * @module model/BlogAdminsResponse
 * @version V1.0
 */
class BlogAdminsResponse {
    /**
     * Constructs a new <code>BlogAdminsResponse</code>.
     * @alias module:model/BlogAdminsResponse
     */
    constructor() { 
        
        BlogAdminsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BlogAdminsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BlogAdminsResponse} obj Optional instance to populate.
     * @return {module:model/BlogAdminsResponse} The populated <code>BlogAdminsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlogAdminsResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('writer')) {
                obj['writer'] = ApiClient.convertToType(data['writer'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BlogAdminsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BlogAdminsResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['writer'] && !(typeof data['writer'] === 'string' || data['writer'] instanceof String)) {
            throw new Error("Expected the field `writer` to be a primitive type in the JSON string but got " + data['writer']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
BlogAdminsResponse.prototype['id'] = undefined;

/**
 * @member {String} writer
 */
BlogAdminsResponse.prototype['writer'] = undefined;

/**
 * @member {String} title
 */
BlogAdminsResponse.prototype['title'] = undefined;

/**
 * @member {String} content
 */
BlogAdminsResponse.prototype['content'] = undefined;

/**
 * @member {Date} createdAt
 */
BlogAdminsResponse.prototype['createdAt'] = undefined;






export default BlogAdminsResponse;

