/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Features model module.
 * @module model/Features
 * @version V1.0
 */
class Features {
    /**
     * Constructs a new <code>Features</code>.
     * @alias module:model/Features
     */
    constructor() { 
        
        Features.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Features</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Features} obj Optional instance to populate.
     * @return {module:model/Features} The populated <code>Features</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Features();

            if (data.hasOwnProperty('rooms')) {
                obj['rooms'] = ApiClient.convertToType(data['rooms'], 'Number');
            }
            if (data.hasOwnProperty('baths')) {
                obj['baths'] = ApiClient.convertToType(data['baths'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Features</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Features</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} rooms
 */
Features.prototype['rooms'] = undefined;

/**
 * @member {Number} baths
 */
Features.prototype['baths'] = undefined;

/**
 * @member {Number} size
 */
Features.prototype['size'] = undefined;






export default Features;

