/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FinancialData model module.
 * @module model/FinancialData
 * @version V1.0
 */
class FinancialData {
    /**
     * Constructs a new <code>FinancialData</code>.
     * @alias module:model/FinancialData
     */
    constructor() { 
        
        FinancialData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FinancialData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FinancialData} obj Optional instance to populate.
     * @return {module:model/FinancialData} The populated <code>FinancialData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FinancialData();

            if (data.hasOwnProperty('rent_price')) {
                obj['rent_price'] = ApiClient.convertToType(data['rent_price'], 'Number');
            }
            if (data.hasOwnProperty('rent_duration')) {
                obj['rent_duration'] = ApiClient.convertToType(data['rent_duration'], 'Number');
            }
            if (data.hasOwnProperty('overall_amount')) {
                obj['overall_amount'] = ApiClient.convertToType(data['overall_amount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FinancialData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FinancialData</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} rent_price
 */
FinancialData.prototype['rent_price'] = undefined;

/**
 * @member {Number} rent_duration
 */
FinancialData.prototype['rent_duration'] = undefined;

/**
 * @member {Number} overall_amount
 */
FinancialData.prototype['overall_amount'] = undefined;






export default FinancialData;

