/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FinancialData from './FinancialData';
import PropertyData from './PropertyData';
import UserData from './UserData';

/**
 * The InitialContractResponse model module.
 * @module model/InitialContractResponse
 * @version V1.0
 */
class InitialContractResponse {
    /**
     * Constructs a new <code>InitialContractResponse</code>.
     * @alias module:model/InitialContractResponse
     */
    constructor() { 
        
        InitialContractResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InitialContractResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InitialContractResponse} obj Optional instance to populate.
     * @return {module:model/InitialContractResponse} The populated <code>InitialContractResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InitialContractResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('expire_at')) {
                obj['expire_at'] = ApiClient.convertToType(data['expire_at'], 'String');
            }
            if (data.hasOwnProperty('owner_data')) {
                obj['owner_data'] = UserData.constructFromObject(data['owner_data']);
            }
            if (data.hasOwnProperty('seeker_data')) {
                obj['seeker_data'] = UserData.constructFromObject(data['seeker_data']);
            }
            if (data.hasOwnProperty('property_data')) {
                obj['property_data'] = PropertyData.constructFromObject(data['property_data']);
            }
            if (data.hasOwnProperty('financial_data')) {
                obj['financial_data'] = FinancialData.constructFromObject(data['financial_data']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InitialContractResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InitialContractResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['created_at'] && !(typeof data['created_at'] === 'string' || data['created_at'] instanceof String)) {
            throw new Error("Expected the field `created_at` to be a primitive type in the JSON string but got " + data['created_at']);
        }
        // ensure the json data is a string
        if (data['expire_at'] && !(typeof data['expire_at'] === 'string' || data['expire_at'] instanceof String)) {
            throw new Error("Expected the field `expire_at` to be a primitive type in the JSON string but got " + data['expire_at']);
        }
        // validate the optional field `owner_data`
        if (data['owner_data']) { // data not null
          UserData.validateJSON(data['owner_data']);
        }
        // validate the optional field `seeker_data`
        if (data['seeker_data']) { // data not null
          UserData.validateJSON(data['seeker_data']);
        }
        // validate the optional field `property_data`
        if (data['property_data']) { // data not null
          PropertyData.validateJSON(data['property_data']);
        }
        // validate the optional field `financial_data`
        if (data['financial_data']) { // data not null
          FinancialData.validateJSON(data['financial_data']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
InitialContractResponse.prototype['id'] = undefined;

/**
 * @member {String} created_at
 */
InitialContractResponse.prototype['created_at'] = undefined;

/**
 * @member {String} expire_at
 */
InitialContractResponse.prototype['expire_at'] = undefined;

/**
 * @member {module:model/UserData} owner_data
 */
InitialContractResponse.prototype['owner_data'] = undefined;

/**
 * @member {module:model/UserData} seeker_data
 */
InitialContractResponse.prototype['seeker_data'] = undefined;

/**
 * @member {module:model/PropertyData} property_data
 */
InitialContractResponse.prototype['property_data'] = undefined;

/**
 * @member {module:model/FinancialData} financial_data
 */
InitialContractResponse.prototype['financial_data'] = undefined;

/**
 * @member {module:model/InitialContractResponse.StatusEnum} status
 */
InitialContractResponse.prototype['status'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
InitialContractResponse['StatusEnum'] = {

    /**
     * value: "PENDING_APPROVAL"
     * @const
     */
    "PENDING_APPROVAL": "PENDING_APPROVAL",

    /**
     * value: "PENDING_PROCESSING"
     * @const
     */
    "PENDING_PROCESSING": "PENDING_PROCESSING",

    /**
     * value: "UNDER_PROCESS"
     * @const
     */
    "UNDER_PROCESS": "UNDER_PROCESS",

    /**
     * value: "COMPLETED"
     * @const
     */
    "COMPLETED": "COMPLETED",

    /**
     * value: "REJECT"
     * @const
     */
    "REJECT": "REJECT",

    /**
     * value: "EXPIRED"
     * @const
     */
    "EXPIRED": "EXPIRED",

    /**
     * value: "BANNED"
     * @const
     */
    "BANNED": "BANNED"
};



export default InitialContractResponse;

