/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InitialContractCreationRequest model module.
 * @module model/InitialContractCreationRequest
 * @version V1.0
 */
class InitialContractCreationRequest {
    /**
     * Constructs a new <code>InitialContractCreationRequest</code>.
     * @alias module:model/InitialContractCreationRequest
     * @param propertyId {String} 
     */
    constructor(propertyId) { 
        
        InitialContractCreationRequest.initialize(this, propertyId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, propertyId) { 
        obj['property_id'] = propertyId;
    }

    /**
     * Constructs a <code>InitialContractCreationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InitialContractCreationRequest} obj Optional instance to populate.
     * @return {module:model/InitialContractCreationRequest} The populated <code>InitialContractCreationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InitialContractCreationRequest();

            if (data.hasOwnProperty('property_id')) {
                obj['property_id'] = ApiClient.convertToType(data['property_id'], 'String');
            }
            if (data.hasOwnProperty('rentDuration')) {
                obj['rentDuration'] = ApiClient.convertToType(data['rentDuration'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InitialContractCreationRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InitialContractCreationRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InitialContractCreationRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['property_id'] && !(typeof data['property_id'] === 'string' || data['property_id'] instanceof String)) {
            throw new Error("Expected the field `property_id` to be a primitive type in the JSON string but got " + data['property_id']);
        }

        return true;
    }


}

InitialContractCreationRequest.RequiredProperties = ["property_id"];

/**
 * @member {String} property_id
 */
InitialContractCreationRequest.prototype['property_id'] = undefined;

/**
 * @member {Number} rentDuration
 */
InitialContractCreationRequest.prototype['rentDuration'] = undefined;






export default InitialContractCreationRequest;

