/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BlogAdminsResponse from './BlogAdminsResponse';

/**
 * The PageResponseBlogAdminsResponse model module.
 * @module model/PageResponseBlogAdminsResponse
 * @version V1.0
 */
class PageResponseBlogAdminsResponse {
    /**
     * Constructs a new <code>PageResponseBlogAdminsResponse</code>.
     * @alias module:model/PageResponseBlogAdminsResponse
     */
    constructor() { 
        
        PageResponseBlogAdminsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PageResponseBlogAdminsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PageResponseBlogAdminsResponse} obj Optional instance to populate.
     * @return {module:model/PageResponseBlogAdminsResponse} The populated <code>PageResponseBlogAdminsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PageResponseBlogAdminsResponse();

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], [BlogAdminsResponse]);
            }
            if (data.hasOwnProperty('totalPages')) {
                obj['totalPages'] = ApiClient.convertToType(data['totalPages'], 'Number');
            }
            if (data.hasOwnProperty('totalElements')) {
                obj['totalElements'] = ApiClient.convertToType(data['totalElements'], 'Number');
            }
            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('last')) {
                obj['last'] = ApiClient.convertToType(data['last'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PageResponseBlogAdminsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PageResponseBlogAdminsResponse</code>.
     */
    static validateJSON(data) {
        if (data['content']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['content'])) {
                throw new Error("Expected the field `content` to be an array in the JSON data but got " + data['content']);
            }
            // validate the optional field `content` (array)
            for (const item of data['content']) {
                BlogAdminsResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/BlogAdminsResponse>} content
 */
PageResponseBlogAdminsResponse.prototype['content'] = undefined;

/**
 * @member {Number} totalPages
 */
PageResponseBlogAdminsResponse.prototype['totalPages'] = undefined;

/**
 * @member {Number} totalElements
 */
PageResponseBlogAdminsResponse.prototype['totalElements'] = undefined;

/**
 * @member {Number} page
 */
PageResponseBlogAdminsResponse.prototype['page'] = undefined;

/**
 * @member {Number} size
 */
PageResponseBlogAdminsResponse.prototype['size'] = undefined;

/**
 * @member {Boolean} last
 */
PageResponseBlogAdminsResponse.prototype['last'] = undefined;






export default PageResponseBlogAdminsResponse;

