/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PropertyPatchRequest model module.
 * @module model/PropertyPatchRequest
 * @version V1.0
 */
class PropertyPatchRequest {
    /**
     * Constructs a new <code>PropertyPatchRequest</code>.
     * @alias module:model/PropertyPatchRequest
     */
    constructor() { 
        
        PropertyPatchRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PropertyPatchRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PropertyPatchRequest} obj Optional instance to populate.
     * @return {module:model/PropertyPatchRequest} The populated <code>PropertyPatchRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PropertyPatchRequest();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('images')) {
                obj['images'] = ApiClient.convertToType(data['images'], [File]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PropertyPatchRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PropertyPatchRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['images'])) {
            throw new Error("Expected the field `images` to be an array in the JSON data but got " + data['images']);
        }

        return true;
    }


}



/**
 * @member {String} title
 */
PropertyPatchRequest.prototype['title'] = undefined;

/**
 * @member {String} description
 */
PropertyPatchRequest.prototype['description'] = undefined;

/**
 * @member {Number} price
 */
PropertyPatchRequest.prototype['price'] = undefined;

/**
 * @member {Array.<File>} images
 */
PropertyPatchRequest.prototype['images'] = undefined;






export default PropertyPatchRequest;

