/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Features from './Features';
import Review from './Review';

/**
 * The PropertyAdminResponse model module.
 * @module model/PropertyAdminResponse
 * @version V1.0
 */
class PropertyAdminResponse {
    /**
     * Constructs a new <code>PropertyAdminResponse</code>.
     * @alias module:model/PropertyAdminResponse
     */
    constructor() { 
        
        PropertyAdminResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PropertyAdminResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PropertyAdminResponse} obj Optional instance to populate.
     * @return {module:model/PropertyAdminResponse} The populated <code>PropertyAdminResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PropertyAdminResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = ApiClient.convertToType(data['owner'], 'String');
            }
            if (data.hasOwnProperty('decription')) {
                obj['decription'] = ApiClient.convertToType(data['decription'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('features')) {
                obj['features'] = Features.constructFromObject(data['features']);
            }
            if (data.hasOwnProperty('coordinates')) {
                obj['coordinates'] = ApiClient.convertToType(data['coordinates'], ['Number']);
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('area')) {
                obj['area'] = ApiClient.convertToType(data['area'], 'String');
            }
            if (data.hasOwnProperty('review')) {
                obj['review'] = Review.constructFromObject(data['review']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PropertyAdminResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PropertyAdminResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['owner'] && !(typeof data['owner'] === 'string' || data['owner'] instanceof String)) {
            throw new Error("Expected the field `owner` to be a primitive type in the JSON string but got " + data['owner']);
        }
        // ensure the json data is a string
        if (data['decription'] && !(typeof data['decription'] === 'string' || data['decription'] instanceof String)) {
            throw new Error("Expected the field `decription` to be a primitive type in the JSON string but got " + data['decription']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // validate the optional field `features`
        if (data['features']) { // data not null
          Features.validateJSON(data['features']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['coordinates'])) {
            throw new Error("Expected the field `coordinates` to be an array in the JSON data but got " + data['coordinates']);
        }
        // ensure the json data is a string
        if (data['city'] && !(typeof data['city'] === 'string' || data['city'] instanceof String)) {
            throw new Error("Expected the field `city` to be a primitive type in the JSON string but got " + data['city']);
        }
        // ensure the json data is a string
        if (data['area'] && !(typeof data['area'] === 'string' || data['area'] instanceof String)) {
            throw new Error("Expected the field `area` to be a primitive type in the JSON string but got " + data['area']);
        }
        // validate the optional field `review`
        if (data['review']) { // data not null
          Review.validateJSON(data['review']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
PropertyAdminResponse.prototype['id'] = undefined;

/**
 * @member {String} title
 */
PropertyAdminResponse.prototype['title'] = undefined;

/**
 * @member {String} owner
 */
PropertyAdminResponse.prototype['owner'] = undefined;

/**
 * @member {String} decription
 */
PropertyAdminResponse.prototype['decription'] = undefined;

/**
 * @member {Number} price
 */
PropertyAdminResponse.prototype['price'] = undefined;

/**
 * @member {module:model/PropertyAdminResponse.TypeEnum} type
 */
PropertyAdminResponse.prototype['type'] = undefined;

/**
 * @member {module:model/PropertyAdminResponse.StatusEnum} status
 */
PropertyAdminResponse.prototype['status'] = undefined;

/**
 * @member {module:model/Features} features
 */
PropertyAdminResponse.prototype['features'] = undefined;

/**
 * @member {Array.<Number>} coordinates
 */
PropertyAdminResponse.prototype['coordinates'] = undefined;

/**
 * @member {String} city
 */
PropertyAdminResponse.prototype['city'] = undefined;

/**
 * @member {String} area
 */
PropertyAdminResponse.prototype['area'] = undefined;

/**
 * @member {module:model/Review} review
 */
PropertyAdminResponse.prototype['review'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
PropertyAdminResponse['TypeEnum'] = {

    /**
     * value: "RENT"
     * @const
     */
    "RENT": "RENT",

    /**
     * value: "PURCHASE"
     * @const
     */
    "PURCHASE": "PURCHASE",

    /**
     * value: "COMMERCIAL_RENT"
     * @const
     */
    "COMMERCIAL_RENT": "COMMERCIAL_RENT",

    /**
     * value: "COMMERCIAL_PURCHASE"
     * @const
     */
    "COMMERCIAL_PURCHASE": "COMMERCIAL_PURCHASE",

    /**
     * value: "STUDENT"
     * @const
     */
    "STUDENT": "STUDENT"
};


/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
PropertyAdminResponse['StatusEnum'] = {

    /**
     * value: "AVAILABLE"
     * @const
     */
    "AVAILABLE": "AVAILABLE",

    /**
     * value: "PENDING_PROCESSING"
     * @const
     */
    "PENDING_PROCESSING": "PENDING_PROCESSING",

    /**
     * value: "COMPLETED"
     * @const
     */
    "COMPLETED": "COMPLETED",

    /**
     * value: "BANNED"
     * @const
     */
    "BANNED": "BANNED"
};



export default PropertyAdminResponse;

