/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Features from './Features';
import GeoJsonPoint from './GeoJsonPoint';
import Image from './Image';
import Location from './Location';
import Review from './Review';

/**
 * The Property model module.
 * @module model/Property
 * @version V1.0
 */
class Property {
    /**
     * Constructs a new <code>Property</code>.
     * @alias module:model/Property
     */
    constructor() { 
        
        Property.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Property</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Property} obj Optional instance to populate.
     * @return {module:model/Property} The populated <code>Property</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Property();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('ownerId')) {
                obj['ownerId'] = ApiClient.convertToType(data['ownerId'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('features')) {
                obj['features'] = Features.constructFromObject(data['features']);
            }
            if (data.hasOwnProperty('mapsLocation')) {
                obj['mapsLocation'] = GeoJsonPoint.constructFromObject(data['mapsLocation']);
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = Location.constructFromObject(data['location']);
            }
            if (data.hasOwnProperty('images')) {
                obj['images'] = ApiClient.convertToType(data['images'], [Image]);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('review')) {
                obj['review'] = Review.constructFromObject(data['review']);
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('deletedAt')) {
                obj['deletedAt'] = ApiClient.convertToType(data['deletedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Property</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Property</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // validate the optional field `features`
        if (data['features']) { // data not null
          Features.validateJSON(data['features']);
        }
        // validate the optional field `mapsLocation`
        if (data['mapsLocation']) { // data not null
          GeoJsonPoint.validateJSON(data['mapsLocation']);
        }
        // validate the optional field `location`
        if (data['location']) { // data not null
          Location.validateJSON(data['location']);
        }
        if (data['images']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['images'])) {
                throw new Error("Expected the field `images` to be an array in the JSON data but got " + data['images']);
            }
            // validate the optional field `images` (array)
            for (const item of data['images']) {
                Image.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // validate the optional field `review`
        if (data['review']) { // data not null
          Review.validateJSON(data['review']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
Property.prototype['id'] = undefined;

/**
 * @member {String} title
 */
Property.prototype['title'] = undefined;

/**
 * @member {Number} price
 */
Property.prototype['price'] = undefined;

/**
 * @member {module:model/Property.TypeEnum} type
 */
Property.prototype['type'] = undefined;

/**
 * @member {Number} ownerId
 */
Property.prototype['ownerId'] = undefined;

/**
 * @member {module:model/Property.StatusEnum} status
 */
Property.prototype['status'] = undefined;

/**
 * @member {module:model/Features} features
 */
Property.prototype['features'] = undefined;

/**
 * @member {module:model/GeoJsonPoint} mapsLocation
 */
Property.prototype['mapsLocation'] = undefined;

/**
 * @member {module:model/Location} location
 */
Property.prototype['location'] = undefined;

/**
 * @member {Array.<module:model/Image>} images
 */
Property.prototype['images'] = undefined;

/**
 * @member {String} description
 */
Property.prototype['description'] = undefined;

/**
 * @member {module:model/Review} review
 */
Property.prototype['review'] = undefined;

/**
 * @member {Date} createdAt
 */
Property.prototype['createdAt'] = undefined;

/**
 * @member {Date} deletedAt
 */
Property.prototype['deletedAt'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
Property['TypeEnum'] = {

    /**
     * value: "RENT"
     * @const
     */
    "RENT": "RENT",

    /**
     * value: "PURCHASE"
     * @const
     */
    "PURCHASE": "PURCHASE",

    /**
     * value: "COMMERCIAL_RENT"
     * @const
     */
    "COMMERCIAL_RENT": "COMMERCIAL_RENT",

    /**
     * value: "COMMERCIAL_PURCHASE"
     * @const
     */
    "COMMERCIAL_PURCHASE": "COMMERCIAL_PURCHASE",

    /**
     * value: "STUDENT"
     * @const
     */
    "STUDENT": "STUDENT"
};


/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
Property['StatusEnum'] = {

    /**
     * value: "AVAILABLE"
     * @const
     */
    "AVAILABLE": "AVAILABLE",

    /**
     * value: "PENDING_PROCESSING"
     * @const
     */
    "PENDING_PROCESSING": "PENDING_PROCESSING",

    /**
     * value: "COMPLETED"
     * @const
     */
    "COMPLETED": "COMPLETED",

    /**
     * value: "BANNED"
     * @const
     */
    "BANNED": "BANNED"
};



export default Property;

