/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PropertyAdPostRequest model module.
 * @module model/PropertyAdPostRequest
 * @version V1.0
 */
class PropertyAdPostRequest {
    /**
     * Constructs a new <code>PropertyAdPostRequest</code>.
     * @alias module:model/PropertyAdPostRequest
     * @param title {String} 
     * @param price {Number} 
     * @param type {module:model/PropertyAdPostRequest.TypeEnum} 
     * @param lng {Number} 
     * @param lat {Number} 
     * @param city {String} 
     * @param area {String} 
     * @param size {Number} 
     */
    constructor(title, price, type, lng, lat, city, area, size) { 
        
        PropertyAdPostRequest.initialize(this, title, price, type, lng, lat, city, area, size);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, price, type, lng, lat, city, area, size) { 
        obj['title'] = title;
        obj['price'] = price;
        obj['type'] = type;
        obj['lng'] = lng;
        obj['lat'] = lat;
        obj['city'] = city;
        obj['area'] = area;
        obj['size'] = size;
    }

    /**
     * Constructs a <code>PropertyAdPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PropertyAdPostRequest} obj Optional instance to populate.
     * @return {module:model/PropertyAdPostRequest} The populated <code>PropertyAdPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PropertyAdPostRequest();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('lng')) {
                obj['lng'] = ApiClient.convertToType(data['lng'], 'Number');
            }
            if (data.hasOwnProperty('lat')) {
                obj['lat'] = ApiClient.convertToType(data['lat'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('rooms')) {
                obj['rooms'] = ApiClient.convertToType(data['rooms'], 'Number');
            }
            if (data.hasOwnProperty('baths')) {
                obj['baths'] = ApiClient.convertToType(data['baths'], 'Number');
            }
            if (data.hasOwnProperty('images')) {
                obj['images'] = ApiClient.convertToType(data['images'], [File]);
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('area')) {
                obj['area'] = ApiClient.convertToType(data['area'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PropertyAdPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PropertyAdPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PropertyAdPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['images'])) {
            throw new Error("Expected the field `images` to be an array in the JSON data but got " + data['images']);
        }
        // ensure the json data is a string
        if (data['city'] && !(typeof data['city'] === 'string' || data['city'] instanceof String)) {
            throw new Error("Expected the field `city` to be a primitive type in the JSON string but got " + data['city']);
        }
        // ensure the json data is a string
        if (data['area'] && !(typeof data['area'] === 'string' || data['area'] instanceof String)) {
            throw new Error("Expected the field `area` to be a primitive type in the JSON string but got " + data['area']);
        }

        return true;
    }


}

PropertyAdPostRequest.RequiredProperties = ["title", "price", "type", "lng", "lat", "city", "area", "size"];

/**
 * @member {String} title
 */
PropertyAdPostRequest.prototype['title'] = undefined;

/**
 * @member {Number} price
 */
PropertyAdPostRequest.prototype['price'] = undefined;

/**
 * @member {module:model/PropertyAdPostRequest.TypeEnum} type
 */
PropertyAdPostRequest.prototype['type'] = undefined;

/**
 * @member {Number} lng
 */
PropertyAdPostRequest.prototype['lng'] = undefined;

/**
 * @member {Number} lat
 */
PropertyAdPostRequest.prototype['lat'] = undefined;

/**
 * @member {String} description
 */
PropertyAdPostRequest.prototype['description'] = undefined;

/**
 * @member {Number} rooms
 */
PropertyAdPostRequest.prototype['rooms'] = undefined;

/**
 * @member {Number} baths
 */
PropertyAdPostRequest.prototype['baths'] = undefined;

/**
 * @member {Array.<File>} images
 */
PropertyAdPostRequest.prototype['images'] = undefined;

/**
 * @member {String} city
 */
PropertyAdPostRequest.prototype['city'] = undefined;

/**
 * @member {String} area
 */
PropertyAdPostRequest.prototype['area'] = undefined;

/**
 * @member {Number} size
 */
PropertyAdPostRequest.prototype['size'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
PropertyAdPostRequest['TypeEnum'] = {

    /**
     * value: "RENT"
     * @const
     */
    "RENT": "RENT",

    /**
     * value: "PURCHASE"
     * @const
     */
    "PURCHASE": "PURCHASE",

    /**
     * value: "COMMERCIAL_RENT"
     * @const
     */
    "COMMERCIAL_RENT": "COMMERCIAL_RENT",

    /**
     * value: "COMMERCIAL_PURCHASE"
     * @const
     */
    "COMMERCIAL_PURCHASE": "COMMERCIAL_PURCHASE",

    /**
     * value: "STUDENT"
     * @const
     */
    "STUDENT": "STUDENT"
};



export default PropertyAdPostRequest;

