/**
 * Property Platform API
 * Api endpoints for property platform
 *
 * The version of the OpenAPI document: V1.0
 * Contact: adisougie@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReviewRequest model module.
 * @module model/ReviewRequest
 * @version V1.0
 */
class ReviewRequest {
    /**
     * Constructs a new <code>ReviewRequest</code>.
     * @alias module:model/ReviewRequest
     */
    constructor() { 
        
        ReviewRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReviewRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReviewRequest} obj Optional instance to populate.
     * @return {module:model/ReviewRequest} The populated <code>ReviewRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReviewRequest();

            if (data.hasOwnProperty('stars')) {
                obj['stars'] = ApiClient.convertToType(data['stars'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReviewRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReviewRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} stars
 */
ReviewRequest.prototype['stars'] = undefined;






export default ReviewRequest;

